version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: run tests
          command: bundle exec rspec
      - run:
          name: deploy site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bin/deploy-ci.sh
            fi
